apiVersion: v1
kind: Service
metadata:
  name: product-similarity-service
spec:
  type: NodePort
  selector:
    app: product-similarity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
